### PR TITLE
Feature 36

### PR DESCRIPTION
**Pull request by etoumey**
* Check DB for latest non-NULL value
* Only launch browser if values are missing
* Only fetch gpx activities if other values are missing

### CODE REVIEW

**Comment by jtoumey** [comment]
Possible bug... running `reportFetch.py` with no _activityArchive_ or _csvArchive_ folder results in what seems to be an infinite loop. 

Screen Shot 2019-10-07 at 9 58 28 PM

**Comment by etoumey** [comment]
@jtoumey reportFetch.py does not use csvArchive or activityArchive. Only parser and tripy do. 

This issue has to do with the fact that you do not have stress reports on Garmin Connect.

**Comment by jtoumey** [comment]
Ah. It seems that after leaving it running for a long time, it's just taking probably minutes for each attempt to find the stress. It took at least an hour to go through 10 stress entries.

**Comment by npbassett** [comment]
When I try to start from scratch (i.e. no userData.db), it only downloads the most recent report.

**Comment by etoumey** [comment]
> When I try to start from scratch (i.e. no userData.db), it only downloads the most recent report.

Yeah... No way around that I can think of....

**Pull request merged**
