### PR TITLE
Add command line input for credentials when the credentials file is n…

### PR DESCRIPTION
**Pull request by jtoumey**
…ot found.

### CODE REVIEW

**Comment by npbassett** [comment]
`raw_input()` was renamed to `input()` in python3, we should use that instead

**Comment by jtoumey** [comment]
> `raw_input()` was renamed to `input()` in python3, we should use that instead

I am not sure the project is python3 compatible, because when I use `input()` instead of `raw_input()`, and then run with python3, I get the following error:

```
jtoumey:bodyStats$ python3 reportFetch.py
  File "reportFetch.py", line 291
    desiredDate = datetime(2019, 5, 01)
                                     ^
SyntaxError: invalid token
```

**Comment by npbassett** [comment]
I believe that can be fixed by removing the preceding 0 in the date

**Comment by jtoumey** [comment]
Ok. So the project is written to the python3 standard?

**Comment by npbassett** [comment]
There's no other python2/3 compatibility issues *that I know of* but there could be some lurking somewhere. But I think we should try to write in python3 in mind as we move forward since python2 end of life is coming soon.

**Comment by jtoumey** [comment]
Great. I'll use 3 moving forward. 

I tested this and it works in my environment.

**Comment by npbassett** [comment]
I get a BrokenPipeError when using the command line login input. Everything works fine when I use credentials.pass. have you run into this on your system?

**Comment by jtoumey** [comment]
It works on my system. At what point do you encounter the error? What does the terminal print out immediately before the error?

**Comment by npbassett** [comment]
It's immediately after loading the credentials during the login process. Here's the full traceback:

> Traceback (most recent call last):
  File "reportFetch.py", line 316, in <module>
    main()
  File "reportFetch.py", line 254, in main
    login(browser)
  File "reportFetch.py", line 184, in login
    browser.get('https://connect.garmin.com/modern/')
  File "/Users/neilbassett/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 326, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/neilbassett/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/neilbassett/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/neilbassett/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 495, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/Users/neilbassett/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/neilbassett/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/neilbassett/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/neilbassett/anaconda3/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/Users/neilbassett/anaconda3/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by jtoumey** [comment]
THANKS. I'll look into it.

**Comment by npbassett** [comment]
Yeah, sorry... What browser are you using? My default is firefox

**Comment by npbassett** [comment]
Nvm, updating selenium seems to have solved the problem. All good on my end now.

**Review by etoumey — APPROVED** [review]

**Pull request merged**
