### PR TITLE
Replace json with SQL in tripy

### LINKED ISSUE #34: Replace json calls with sqlite in tripy

### PR DESCRIPTION
**Pull request by etoumey**
This is a pull request to fix https://github.com/etoumey/bodyStats/issues/34

ATL, CTL and TSS are now fields in the database. Tripy will propagate ATL and CTL from the last null value up until

### CODE REVIEW

**Comment by jtoumey** [comment]
I've encountered a few issues unrelated to this update on branch `eliot`...
1. _parser.py_ is not python3 compatible
Screen Shot 2019-10-05 at 10 14 24 AM

2. In _parser.py_, there may be an missing argument to a function call
Screen Shot 2019-10-05 at 10 14 55 AM

**Comment by jtoumey** [comment]
Tried to run in python2 and got this error:

Screen Shot 2019-10-05 at 10 27 21 AM

**Comment by etoumey** [comment]
oh boy. I'll take a look

**Comment by jtoumey** [comment]
COOL I got it to run with python3. My py2 is unusable for some reason. 

* Recommend to suppress the `pdflatex` output. 
* Encountered a warning when updating the database with many files which may need to be handled: 
```
tripy.py:203: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure()
```
* Would recommend appending a time stamp to the figure filenames or in the figure titles so that on quick perusal, one may know when they were generated.
* Similar to above, would recommend appending an activity name/date to the HR plots

**Review by jtoumey — APPROVED** [review]
As far as I can tell it looks good. It definitely runs for me and generates usable output when I use python3. I left some comments which are just recommendations, but you don't have to address them.

**Pull request merged**
