### PR TITLE
Neil

### PR DESCRIPTION
**Pull request by npbassett**
This contains two new features that I probably should have separated but...I didn't. 
1. Tripy now adds distance, elevation gain, and elapsed time for each activity into database.
2. Created a new Plotter class within plot.py which loads data from DB and has various functions to create plots including plotRHR() from before and new cumulative plots of distance/elev/etc.

### CODE REVIEW

**Review by etoumey — CHANGES_REQUESTED** [review]
It looks like you need to account for leap years.

**Comment by etoumey** [comment]
Also, I'm not happy with added more fields to the userData table. The activity specific information needs to be in it's own table.

**Comment by npbassett** [comment]
> It looks like you need to account for leap years.

Yeah, but it works for _my_ data right now...

> The activity specific information needs to be in it's own table.

Why?

**Comment by etoumey** [comment]
> > It looks like you need to account for leap years.
> 
> Yeah, but it works for _my_ data right now...
> 
It doesn't work for my data
> > The activity specific information needs to be in it's own table.
> 
> Why?
>
So that multiple activities can be uploaded for the same day.

**Comment by npbassett** [comment]
> The activity specific information needs to be in it's own table.
>> Why?
>>> So that multiple activities can be uploaded for the same day.

If you insist, honey. May take a bit since I'm not all that familiar with SQL.

**Comment by etoumey** [comment]
@npbassett  no, there is already a separate issue to handle that part. (https://github.com/etoumey/bodyStats/issues/47). Each PR needs to be specifically in reference to one issue, so just leave it as is.

I will keep working through the PR as is. It still isn't working for me, but I will look through some more tomorrow.

**Pull request merged**
